version: '3.8'
services:

  metabase:
    image: metabase/metabase:v0.49.0
    container_name: metabase
    hostname: metabase
    volumes:
      - /dev/urandom:/dev/random:ro
    ports:
      - '3000:3000' 
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase-db
      MB_DB_PORT: 5432
      MB_DB_USER: user
      MB_DB_PASS: dbpassword
      MB_DB_HOST: postgres
      MB_ENCRYPTION_SECRET_KEY: ${MB_ENCRYPTION_SECRET_KEY}
    networks:
      - metanet
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    container_name: postgres
    hostname: postgres
    environment:
      POSTGRES_DB: metabase-db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: dbpassword
      PGDATA: /var/lib/postgresql/db
    volumes:
      - /opt/databases/prod/metabase/postgresql/db:/var/lib/postgresql/db
    networks:
      - metanet
    restart: unless-stopped

networks:
  metanet:
    driver: bridge
